# Base image
ARG BASE_IMAGE_URL=nvcr.io/nvidia/base/ubuntu
ARG BASE_IMAGE_TAG=22.04_20240212

FROM ${BASE_IMAGE_URL}:${BASE_IMAGE_TAG}

# Image metadata
LABEL maintainer="NVIDIA"
LABEL description="Voice Agent example for Agentic Patient Front Desk Assistant"
LABEL version="1.0"

# Environment setup
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND noninteractive

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglx-mesa0 \
    curl \
    ffmpeg \
    git 

# install python3.12
RUN apt update && \
    apt install -y curl software-properties-common  && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt update && apt install -y python3.12 && \
    apt-get clean

# Install pip for python3.12
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12

RUN rm -rf /var/lib/apt/lists/* 

# Install pip and uv
RUN pip install --upgrade pip uv

# clone the ace-controller repository 
WORKDIR /
RUN git clone https://github.com/NVIDIA/ace-controller.git -b develop-health

# App directory setup
WORKDIR /ace-controller

# App files
COPY ./ ./examples/healthcare_agent/

# Example app directory
WORKDIR /ace-controller/examples/healthcare_agent

# Dependencies
RUN uv sync --frozen

# Port configuration
EXPOSE 7860

# Start command
CMD ["uv", "run", "pipeline-patient.py"]
